apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: argo-workflows
    meta.helm.sh/release-namespace: argo
  labels:
    app.kubernetes.io/component: workflow-controller
    app.kubernetes.io/instance: argo-workflows
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-workflows-workflow-controller
    app.kubernetes.io/part-of: argo-workflows
    app.kubernetes.io/version: v3.4.11
    helm.sh/chart: argo-workflows-0.33.3
  name: argo-workflows-workflow-controller
  namespace: argo
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/instance: argo-workflows
    app.kubernetes.io/name: argo-workflows-workflow-controller
  sessionAffinity: None
  type: ClusterIP
