{
 "title": "rpu_workflows",
 "description": "RPU Workflow level dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "workflow_status",
    "query": {
     "query": "label_values(argo_workflows_rpu_workflow_result_counter,status)"
    }
   },
   {
    "name": "workflow_namespace",
    "label": "workflow_namespace",
    "query": {
     "query": "label_values(argo_workflows_rpu_workflow_result_counter,workflow_namespace)"
    }
   },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(argo_workflows_rpu_workflow_result_counter,job_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Workflow Duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(argo_workflows_rpu_workflow_duration_gauge)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPU workflows top K duration",
   "type": "table",
   "description": "Displays workflows with top K duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, argo_workflows_rpu_workflow_duration_gauge{job_name=\"$job_name\", workflow_namespace=\"$workflow_namespace\", status=\"$workflow_status\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPU workflows by Status and Namespace",
   "type": "table",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "argo_workflows_rpu_workflow_result_counter{workflow_namespace=\"$workflow_namespace\", status=\"$workflow_status\", job_name=\"$job_name\"}",
     "legendFormat": "{{job_id, job_name}}"
    }
   ]
  }
 ]
}