{
 "title": "rpu_workflows",
 "description": "RPU Workflow level dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "workflow_status",
    "query": {
     "query": "label_values(argo_workflows_rpu_workflows_result_counter,status)"
    }
   },
   {
    "name": "workflow_namespace",
    "label": "workflow_namespace",
    "query": {
     "query": "label_values(argo_workflows_rpu_workflows_result_counter,workflow_namespace)"
    }
   },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(argo_workflows_rpu_workflows_result_counter,job_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argo_workflows_rpu_workflows_result_counter{status=\"$workflow_status\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Workflow Duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(argo_workflows_rpu_workflows_duration_gauge{status=\"$workflow_status\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(argo_workflows_rpu_workflows_result_counter{status=\"$workflow_status\", workflow_namespace=\"$workflow_namespace\", job_name=\"$job_name\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}