{
 "title": "rpu_tasks",
 "description": "RPU tasks",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "task_name",
    "query": {
     "query": "label_values(argo_workflows_rpu_task_result_counter,task_name)"
    }
   },
   {
    "name": "task_status",
    "query": {
     "query": "label_values(argo_workflows_rpu_task_result_counter,task_status)"
    }
   },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(argo_workflows_rpu_task_result_counter,job_name)"
    }
   },
   {
    "name": "workflow_namespace",
    "query": {
     "query": "label_values(argo_workflows_rpu_task_result_counter,workflow_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Task Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(task_name) (argo_workflows_rpu_task_duration_gauge{task_status=\"$task_status\", job_name=\"$job_name\", workflow_namespace=\"$workflow_namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "\"$task_name\" Task Average Duration by Docker Version",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(docker_version) (argo_workflows_rpu_task_duration_gauge{job_name=\"$job_name\", workflow_namespace=\"$workflow_namespace\", task_status=\"$task_status\", task_name=\"$task_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$task_status rate by tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(argo_workflows_rpu_task_result_counter{task_status=\"$task_status\"}[1m])) by (task_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Duration Overtime",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(argo_workflows_rpu_task_duration_gauge{job_name=\"$job_name\",workflow_namespace=\"$workflow_namespace\",task_name=\"$task_name\", task_status=\"$task_status\" }) without (docker_version,pod, container,endpoint)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}