apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: raas-argo-workflows
    meta.helm.sh/release-namespace: raas-argo-workflows
  labels:
    app.kubernetes.io/component: workflow-controller
    app.kubernetes.io/instance: raas-argo-workflows
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-workflows-workflow-controller
    app.kubernetes.io/part-of: argo-workflows
    helm.sh/chart: argo-workflows-0.33.2
  name: raas-argo-workflows-workflow-controller
  namespace: raas-argo-workflows
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
    - interval: 30s
      path: /telemetry
      port: telemetry
  namespaceSelector:
    matchNames:
      - raas-argo-workflows
  selector:
    matchLabels:
      app.kubernetes.io/instance: raas-argo-workflows
      app.kubernetes.io/name: argo-workflows-workflow-controller
