apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: raas-argo-workflows
    meta.helm.sh/release-namespace: raas-argo-workflows
  labels:
    app.kubernetes.io/component: workflow-controller
    app.kubernetes.io/instance: raas-argo-workflows
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-workflows-workflow-controller
    app.kubernetes.io/part-of: argo-workflows
    app.kubernetes.io/version: v3.4.11
    helm.sh/chart: argo-workflows-0.33.2
  name: raas-argo-workflows-workflow-controller
  namespace: raas-argo-workflows
spec:
  clusterIP: 10.100.47.36
  clusterIPs:
    - 10.100.47.36
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 9090
    - name: telemetry
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/instance: raas-argo-workflows
    app.kubernetes.io/name: argo-workflows-workflow-controller
  sessionAffinity: None
  type: ClusterIP
